spring.application.name=OrderFlow

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/OrderFlow
spring.datasource.username=root
spring.datasource.password=root

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
